language: node_js
node_js:
 - "node"
notifications:
  recipients:
    - alexanderlapygin@gmail.com
  email:
    on_success: always
    on_failure: always
  deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
