language: node_js
node_js:
 - "node"
notifications:
  email:
    - alexanderlapygin@gmail.com
    - sftspider@gmail.com
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app:
    master: node-travis-heroku-cd1
